import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tera Raid Type Chart and Egg Timer",
  description: "Generated by create next app",
  referrer: "same-origin",
  icons: { icon: "favicon.ico" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
